CREATE TABLE [Driver] (
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[DriverCode] VARCHAR(10) NOT NULL,
	[Name] VARCHAR(75) NOT NULL,
	[Type] VARCHAR(20) NOT NULL,
	[Category] VARCHAR(20) NOT NULL,
	[CheckIn] DATETIME,
	[Yard] VARCHAR(36)
)