CREATE TABLE [dbo].[Location] (
    [ID]      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Name]    VARCHAR (125)    NOT NULL,
    [Address] VARCHAR (500)    NOT NULL,
    [Country] UNIQUEIDENTIFIER NOT NULL, 
    [State] UNIQUEIDENTIFIER NOT NULL, 
    [City] UNIQUEIDENTIFIER NOT NULL, 
    [Street] VARCHAR(75) NOT NULL, 
    [ZipCode] VARCHAR(7) NOT NULL
);