CREATE TABLE [Notification] (
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Description] VARCHAR(255) NOT NULL,
	[Group] UNIQUEIDENTIFIER NOT NULL,
	[Created] DATETIME NOT NULL,
	[Resends] INT NOT NULL,
	[Resended] DATETIME,
	[Origin] UNIQUEIDENTIFIER
)